yarnPath: .yarn/releases/yarn-3.5.1.cjs
# packageExtensions:
#   '@eslint-plugin-flowtype@*':
#     peerDependencies:
#       '@babel/plugin-syntax-flow': '*'
#       '@babel/plugin-transform-react-jsx': '*'
#   '@testing-library/user-event@*':
#     peerDependencies:
#       '@testing-library/dom': '*'
